# Generated by Django 6.0.5 on 2026-05-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_code', models.CharField(max_length=50, unique=True)),
                ('plate_number', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('current_mileage', models.PositiveIntegerField(default=0)),
                ('fuel_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('oil_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('battery_health', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('assigned_driver', models.CharField(blank=True, max_length=100, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('REPAIR', 'In Repair'), ('OVERDUE', 'Overdue')], default='READY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
