# Generated by Django 6.0.6 on 2026-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicle_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_month_km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='kt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_recorded_mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
