# Generated by Django 6.0.6 on 2026-06-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicle_current_month_km_vehicle_kt_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='current_mileage',
            new_name='monthly_end_mileage',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='current_month_km',
            new_name='monthly_start_mileage',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_recorded_mileage',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='month',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
